bp_teams = [];
bp_overall = {
    "SessionStartTime": "2024-04-27T14:29:54.275041+01:00",
    "ResultAvailable": true,
    "ShowNotifications": true,
    "EventId": 20637,
    "EventUuid": "d5e76ae8-23f6-4258-86fc-ca6ea01beb96",
    "SessionId": 49349,
    "SessionUuid": "0458e6cf-fddc-4a9c-911b-1433b21a3bc5",
    "SessionName": "24HR 2024",
    "SessionType": "Race",
    "CircuitMap": "buckmore_park",
    "tl": 1000,
    "tn": "International",
    "Weather": null,
    "Temperature": null,
    "TrackCondition": null,
    "IsTeamEvent": false,
    "MultiCls": false,
    "ns": null,
    "nst": null,
    "bn": null,
    "bst": null,
    "bet": null,
    "officials": [],
    "dp": 3,
    "blt": {
        "cn": "12",
        "cnpb": "#0094D9",
        "cnpf": "#FFFFFF",
        "ln": 51,
        "tm": 48848
    },
    "bs1": {
        "cn": "5",
        "cnpb": "#0094D9",
        "cnpf": "#FFFFFF",
        "ln": 92,
        "tm": 19933
    },
    "bs2": {
        "cn": "12",
        "cnpb": "#0094D9",
        "cnpf": "#FFFFFF",
        "ln": 11,
        "tm": 14209
    },
    "bs3": {
        "cn": "11",
        "cnpb": "#0094D9",
        "cnpf": "#FFFFFF",
        "ln": 131,
        "tm": 14357
    },
    "tt": 0.0,
    "SD": "24h",
    "flds": [
        "gd",
        "ps",
        "lpe"
    ],
    "nto": -0.235,
    "ntst": "2024-04-28T13:36:25.346Z",
    "ntip": "132.163.96.6",
    "ntsn": "time.nist.gov",
    "State": "Ended",
    "fcy": false,
    "Sequence": 113628,
    "Sectors": 3,
    "RaceTime": 86462,
    "Rd": "0",
    "Last": false,
    "End": true,
    "show_race_time": true,
    "TimingSystem": "buckmore",
    "Date": "2024-04-27",
    "Sessions": [
        {
            "SessionId": 49348,
            "SessionUuid": "d28acb6a-3003-4920-ab2f-1e137df4222d",
            "SessionName": "Qualifying",
            "SessionType": "Practice",
            "SessionStartTime": "2024-04-27T12:47:31.582Z",
            "EventId": 20637,
            "EventUuid": "d5e76ae8-23f6-4258-86fc-ca6ea01beb96",
            "VersionNumber": -1,
            "EventDate": "2024-04-27"
        },
        {
            "SessionId": 49354,
            "SessionUuid": "8413c683-ebbf-402d-b39d-23b870f4e6aa",
            "SessionName": "Practice",
            "SessionType": "Practice",
            "SessionStartTime": "2024-04-27T11:18:00.620Z",
            "EventId": 20637,
            "EventUuid": "d5e76ae8-23f6-4258-86fc-ca6ea01beb96",
            "VersionNumber": -1,
            "EventDate": "2024-04-27"
        }
    ],
    "Clear": false,
    "Competitors": [
        {
            "CompetitorId": 610121,
            "CompetitorNumber": "11",
            "CompetitorName": "Nameless Motorsport",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 1,
            "NumberOfLaps": 1347,
            "LastLaptime": 50240,
            "RaceTime": 86411357,
            "RunningTime": 86411357,
            "BestLaptime": 48929,
            "BestLapNumber": 93,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 3,
            "PositionChange": 0,
            "Gap": "",
            "gd": 0,
            "Behind": "",
            "Split1": 20943,
            "Split2": 14487,
            "Split3": 14810,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50240,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 13,
            "lpe": 82959951,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 26793,
            "es2": 17146,
            "es3": 14810
        },
        {
            "CompetitorId": 610119,
            "CompetitorNumber": "4",
            "CompetitorName": "XLR8 Kent Brewery Racing",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 2,
            "NumberOfLaps": 1343,
            "LastLaptime": 50122,
            "RaceTime": 86447599,
            "RunningTime": 86447599,
            "BestLaptime": 48953,
            "BestLapNumber": 96,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 1,
            "PositionChange": 0,
            "Gap": "4 Laps",
            "gd": -118,
            "Behind": "4 Laps",
            "Split1": 20909,
            "Split2": 14547,
            "Split3": 14666,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50122,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 13,
            "lpe": 81940217,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20909,
            "es2": 14547,
            "es3": 14666
        },
        {
            "CompetitorId": 610118,
            "CompetitorNumber": "5",
            "CompetitorName": "Dab Motorsport",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 3,
            "NumberOfLaps": 1343,
            "LastLaptime": 50131,
            "RaceTime": 86452584,
            "RunningTime": 86452584,
            "BestLaptime": 48891,
            "BestLapNumber": 103,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 0,
            "PositionChange": 0,
            "Gap": "4.985",
            "gd": 9,
            "Behind": "4 Laps",
            "Split1": 20833,
            "Split2": 14526,
            "Split3": 14772,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50131,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 15,
            "lpe": 82304959,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20833,
            "es2": 14526,
            "es3": 14772
        },
        {
            "CompetitorId": 610123,
            "CompetitorNumber": "13",
            "CompetitorName": "The Only Way Is Brentwood",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 4,
            "NumberOfLaps": 1335,
            "LastLaptime": 49896,
            "RaceTime": 86446905,
            "RunningTime": 86446905,
            "BestLaptime": 49001,
            "BestLapNumber": 15,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 5,
            "PositionChange": 0,
            "Gap": "8 Laps",
            "gd": 379,
            "Behind": "12 Laps",
            "Split1": 20724,
            "Split2": 14520,
            "Split3": 14652,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 49896,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 15,
            "lpe": 82800870,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20724,
            "es2": 14520,
            "es3": 14652
        },
        {
            "CompetitorId": 610131,
            "CompetitorNumber": "2",
            "CompetitorName": "TRX Motorsport Elite",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 5,
            "NumberOfLaps": 1330,
            "LastLaptime": 50085,
            "RaceTime": 86450715,
            "RunningTime": 86450715,
            "BestLaptime": 49403,
            "BestLapNumber": 45,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 13,
            "PositionChange": 0,
            "Gap": "5 Laps",
            "gd": 189,
            "Behind": "17 Laps",
            "Split1": 20768,
            "Split2": 14444,
            "Split3": 14873,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50085,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 13,
            "lpe": 85225608,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20768,
            "es2": 14444,
            "es3": 14873
        },
        {
            "CompetitorId": 610124,
            "CompetitorNumber": "25",
            "CompetitorName": "Ditch Finders",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 6,
            "NumberOfLaps": 1327,
            "LastLaptime": 51343,
            "RaceTime": 86440713,
            "RunningTime": 86440713,
            "BestLaptime": 49327,
            "BestLapNumber": 54,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 6,
            "PositionChange": 0,
            "Gap": "3 Laps",
            "gd": 1405,
            "Behind": "20 Laps",
            "Split1": 21572,
            "Split2": 14601,
            "Split3": 15170,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 51343,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 14,
            "lpe": 85210980,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 21572,
            "es2": 14601,
            "es3": 15170
        },
        {
            "CompetitorId": 610137,
            "CompetitorNumber": "7",
            "CompetitorName": "The Slidemen",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 7,
            "NumberOfLaps": 1326,
            "LastLaptime": 50184,
            "RaceTime": 86420473,
            "RunningTime": 86420473,
            "BestLaptime": 49636,
            "BestLapNumber": 5,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 19,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": -717,
            "Behind": "21 Laps",
            "Split1": 26428,
            "Split2": 17353,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 58732,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 17,
            "lpe": 82079176,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 26428,
            "es2": 17353,
            "es3": 14951
        },
        {
            "CompetitorId": 610129,
            "CompetitorNumber": "10",
            "CompetitorName": "EKS All-Stars",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 8,
            "NumberOfLaps": 1326,
            "LastLaptime": 49934,
            "RaceTime": 86421760,
            "RunningTime": 86421760,
            "BestLaptime": 48925,
            "BestLapNumber": 118,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 11,
            "PositionChange": 0,
            "Gap": "1.287",
            "gd": -250,
            "Behind": "21 Laps",
            "Split1": 28212,
            "Split2": 18475,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 61397,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 16,
            "lpe": 82049329,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 28212,
            "es2": 18475,
            "es3": 14710
        },
        {
            "CompetitorId": 610122,
            "CompetitorNumber": "8",
            "CompetitorName": "Buro 11 NFS",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 9,
            "NumberOfLaps": 1324,
            "LastLaptime": 49628,
            "RaceTime": 86411632,
            "RunningTime": 86411632,
            "BestLaptime": 49143,
            "BestLapNumber": 92,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 4,
            "PositionChange": 0,
            "Gap": "2 Laps",
            "gd": -336,
            "Behind": "23 Laps",
            "Split1": 25752,
            "Split2": 15263,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 55612,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 22,
            "lpe": 83868708,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 25752,
            "es2": 15263,
            "es3": 14597
        },
        {
            "CompetitorId": 610132,
            "CompetitorNumber": "3",
            "CompetitorName": "Toby and the Bandits",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 10,
            "NumberOfLaps": 1322,
            "LastLaptime": 50317,
            "RaceTime": 86454219,
            "RunningTime": 86454219,
            "BestLaptime": 49463,
            "BestLapNumber": 9,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 14,
            "PositionChange": 0,
            "Gap": "2 Laps",
            "gd": 689,
            "Behind": "25 Laps",
            "Split1": 20733,
            "Split2": 14594,
            "Split3": 14990,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50317,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 14,
            "lpe": 79160169,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20733,
            "es2": 14594,
            "es3": 14990
        },
        {
            "CompetitorId": 610127,
            "CompetitorNumber": "1",
            "CompetitorName": "Team ARD",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 11,
            "NumberOfLaps": 1321,
            "LastLaptime": 49867,
            "RaceTime": 86447229,
            "RunningTime": 86447229,
            "BestLaptime": 49497,
            "BestLapNumber": 87,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 9,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": -462,
            "Behind": "26 Laps",
            "Split1": 20723,
            "Split2": 14381,
            "Split3": 14763,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 49867,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 15,
            "lpe": 82195153,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20723,
            "es2": 14381,
            "es3": 14763
        },
        {
            "CompetitorId": 610125,
            "CompetitorNumber": "19",
            "CompetitorName": "Spicy Bois ",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 12,
            "NumberOfLaps": 1320,
            "LastLaptime": 50779,
            "RaceTime": 86413589,
            "RunningTime": 86413589,
            "BestLaptime": 49457,
            "BestLapNumber": 92,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 7,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": 809,
            "Behind": "27 Laps",
            "Split1": 21038,
            "Split2": 15045,
            "Split3": 14696,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50779,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 14,
            "lpe": 81935453,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 24972,
            "es2": 17180,
            "es3": 14696
        },
        {
            "CompetitorId": 610135,
            "CompetitorNumber": "14",
            "CompetitorName": "Zesty Drink Racing",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 13,
            "NumberOfLaps": 1320,
            "LastLaptime": 50031,
            "RaceTime": 86453304,
            "RunningTime": 86453304,
            "BestLaptime": 49338,
            "BestLapNumber": 58,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 17,
            "PositionChange": 0,
            "Gap": "39.715",
            "gd": -748,
            "Behind": "27 Laps",
            "Split1": 20858,
            "Split2": 14536,
            "Split3": 14637,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50031,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 15,
            "lpe": 81674531,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20858,
            "es2": 14536,
            "es3": 14637
        },
        {
            "CompetitorId": 610136,
            "CompetitorNumber": "29",
            "CompetitorName": "Sénor Frogs",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 14,
            "NumberOfLaps": 1319,
            "LastLaptime": 50994,
            "RaceTime": 86412941,
            "RunningTime": 86412941,
            "BestLaptime": 49616,
            "BestLapNumber": 67,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 18,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": 921,
            "Behind": "28 Laps",
            "Split1": 21227,
            "Split2": 14817,
            "Split3": 14950,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50994,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 12,
            "lpe": 78448246,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 24534,
            "es2": 15986,
            "es3": 14950
        },
        {
            "CompetitorId": 610126,
            "CompetitorNumber": "9",
            "CompetitorName": "Loughborough Legends \u0026 Neil",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 15,
            "NumberOfLaps": 1318,
            "LastLaptime": 50234,
            "RaceTime": 86451076,
            "RunningTime": 86451076,
            "BestLaptime": 49295,
            "BestLapNumber": 60,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 8,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": -760,
            "Behind": "29 Laps",
            "Split1": 20940,
            "Split2": 14621,
            "Split3": 14673,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50234,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 16,
            "lpe": 81106246,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 20940,
            "es2": 14621,
            "es3": 14673
        },
        {
            "CompetitorId": 610134,
            "CompetitorNumber": "16",
            "CompetitorName": "Elite Disco’s Racing ",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 16,
            "NumberOfLaps": 1316,
            "LastLaptime": 50625,
            "RaceTime": 86413062,
            "RunningTime": 86413062,
            "BestLaptime": 49487,
            "BestLapNumber": 28,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 16,
            "PositionChange": 0,
            "Gap": "2 Laps",
            "gd": 567,
            "Behind": "31 Laps",
            "Split1": 21099,
            "Split2": 14719,
            "Split3": 14807,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50625,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 14,
            "lpe": 81175389,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 24724,
            "es2": 16126,
            "es3": 14807
        },
        {
            "CompetitorId": 610138,
            "CompetitorNumber": "15",
            "CompetitorName": "Fat and Furious",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 17,
            "NumberOfLaps": 1316,
            "LastLaptime": 51112,
            "RaceTime": 86440589,
            "RunningTime": 86440589,
            "BestLaptime": 49463,
            "BestLapNumber": 87,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 20,
            "PositionChange": 0,
            "Gap": "27.527",
            "gd": 487,
            "Behind": "31 Laps",
            "Split1": 21233,
            "Split2": 14700,
            "Split3": 15179,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 51112,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 15,
            "lpe": 79255344,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 21233,
            "es2": 14700,
            "es3": 15179
        },
        {
            "CompetitorId": 610133,
            "CompetitorNumber": "24",
            "CompetitorName": "1322 Racing North East",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 18,
            "NumberOfLaps": 1316,
            "LastLaptime": 50928,
            "RaceTime": 86458723,
            "RunningTime": 86458723,
            "BestLaptime": 49381,
            "BestLapNumber": 87,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 15,
            "PositionChange": 0,
            "Gap": "18.134",
            "gd": -184,
            "Behind": "31 Laps",
            "Split1": 21084,
            "Split2": 14890,
            "Split3": 14954,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50928,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 13,
            "lpe": 85328872,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 21084,
            "es2": 14890,
            "es3": 14954
        },
        {
            "CompetitorId": 610141,
            "CompetitorNumber": "17",
            "CompetitorName": "Formula None",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 19,
            "NumberOfLaps": 1314,
            "LastLaptime": 50959,
            "RaceTime": 86440321,
            "RunningTime": 86440321,
            "BestLaptime": 49448,
            "BestLapNumber": 64,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 23,
            "PositionChange": 0,
            "Gap": "2 Laps",
            "gd": 317,
            "Behind": "33 Laps",
            "Split1": 20945,
            "Split2": 14955,
            "Split3": 15059,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50959,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 16,
            "lpe": 78564256,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 20945,
            "es2": 14955,
            "es3": 15059
        },
        {
            "CompetitorId": 610120,
            "CompetitorNumber": "12",
            "CompetitorName": "Team Rango with Red M1st",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Pro",
            "DriverName": null,
            "Position": 20,
            "NumberOfLaps": 1313,
            "LastLaptime": 51171,
            "RaceTime": 86423724,
            "RunningTime": 86423724,
            "BestLaptime": 48848,
            "BestLapNumber": 51,
            "IsBestLapInRace": true,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 2,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": -246,
            "Behind": "34 Laps",
            "Split1": 27354,
            "Split2": 19990,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 62680,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 19,
            "lpe": 82627626,
            "nbc": "#0094D9",
            "nfc": "#FFFFFF",
            "es1": 27354,
            "es2": 19990,
            "es3": 15336
        },
        {
            "CompetitorId": 610140,
            "CompetitorNumber": "6",
            "CompetitorName": "TRX Motorsport Pro",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 21,
            "NumberOfLaps": 1305,
            "LastLaptime": 51362,
            "RaceTime": 86441775,
            "RunningTime": 86441775,
            "BestLaptime": 50150,
            "BestLapNumber": 72,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 22,
            "PositionChange": 0,
            "Gap": "8 Laps",
            "gd": 191,
            "Behind": "42 Laps",
            "Split1": 21144,
            "Split2": 14966,
            "Split3": 15252,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 51362,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 13,
            "lpe": 85081409,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 21144,
            "es2": 14966,
            "es3": 15252
        },
        {
            "CompetitorId": 610147,
            "CompetitorNumber": "30",
            "CompetitorName": "Quadrant",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 22,
            "NumberOfLaps": 1296,
            "LastLaptime": 52432,
            "RaceTime": 86461550,
            "RunningTime": 86461550,
            "BestLaptime": 50993,
            "BestLapNumber": 93,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 29,
            "PositionChange": 0,
            "Gap": "9 Laps",
            "gd": 1070,
            "Behind": "51 Laps",
            "Split1": 21743,
            "Split2": 15464,
            "Split3": 15225,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 52432,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 22,
            "lpe": 80343338,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 21743,
            "es2": 15464,
            "es3": 15225
        },
        {
            "CompetitorId": 610130,
            "CompetitorNumber": "26",
            "CompetitorName": "BN Racing",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 23,
            "NumberOfLaps": 1295,
            "LastLaptime": 50199,
            "RaceTime": 86448398,
            "RunningTime": 86448398,
            "BestLaptime": 49203,
            "BestLapNumber": 72,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 12,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": -1493,
            "Behind": "52 Laps",
            "Split1": 21000,
            "Split2": 14420,
            "Split3": 14779,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 50199,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 14,
            "lpe": 79453864,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 21000,
            "es2": 14420,
            "es3": 14779
        },
        {
            "CompetitorId": 610143,
            "CompetitorNumber": "23",
            "CompetitorName": "MPMC",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 24,
            "NumberOfLaps": 1294,
            "LastLaptime": 51401,
            "RaceTime": 86416551,
            "RunningTime": 86416551,
            "BestLaptime": 49516,
            "BestLapNumber": 71,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 25,
            "PositionChange": 0,
            "Gap": "1 Lap",
            "gd": 1519,
            "Behind": "53 Laps",
            "Split1": 26141,
            "Split2": 18157,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 59508,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 14,
            "lpe": 77975517,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 26141,
            "es2": 18157,
            "es3": 15210
        },
        {
            "CompetitorId": 610139,
            "CompetitorNumber": "22",
            "CompetitorName": "The Sporting Club",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 25,
            "NumberOfLaps": 1286,
            "LastLaptime": 52374,
            "RaceTime": 86435171,
            "RunningTime": 86435171,
            "BestLaptime": 49574,
            "BestLapNumber": 81,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 21,
            "PositionChange": 0,
            "Gap": "8 Laps",
            "gd": 973,
            "Behind": "61 Laps",
            "Split1": 21841,
            "Split2": 15127,
            "Split3": 15406,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 52374,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 20,
            "lpe": 80934752,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 21841,
            "es2": 15127,
            "es3": 15406
        },
        {
            "CompetitorId": 610128,
            "CompetitorNumber": "20",
            "CompetitorName": "Sainz Sealed Delivered",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 26,
            "NumberOfLaps": 1279,
            "LastLaptime": 50363,
            "RaceTime": 86412503,
            "RunningTime": 86412503,
            "BestLaptime": 49437,
            "BestLapNumber": 69,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 10,
            "PositionChange": 0,
            "Gap": "7 Laps",
            "gd": -1913,
            "Behind": "68 Laps",
            "Split1": 23076,
            "Split2": 16026,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 53942,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 24,
            "lpe": 82858926,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 23076,
            "es2": 16026,
            "es3": 14840
        },
        {
            "CompetitorId": 610142,
            "CompetitorNumber": "18",
            "CompetitorName": "TRX Motorsport Academy",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 27,
            "NumberOfLaps": 1275,
            "LastLaptime": 51079,
            "RaceTime": 86423844,
            "RunningTime": 86423844,
            "BestLaptime": 49773,
            "BestLapNumber": 1273,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 24,
            "PositionChange": 0,
            "Gap": "4 Laps",
            "gd": 716,
            "Behind": "72 Laps",
            "Split1": 26542,
            "Split2": 20272,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 62144,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 21,
            "lpe": 79611229,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 26542,
            "es2": 20272,
            "es3": 15330
        },
        {
            "CompetitorId": 610146,
            "CompetitorNumber": "28",
            "CompetitorName": "Slick and Tyred",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 28,
            "NumberOfLaps": 1257,
            "LastLaptime": 50362,
            "RaceTime": 86424686,
            "RunningTime": 86424686,
            "BestLaptime": 49889,
            "BestLapNumber": 1254,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 28,
            "PositionChange": 0,
            "Gap": "18 Laps",
            "gd": -717,
            "Behind": "90 Laps",
            "Split1": 26743,
            "Split2": 19969,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 61681,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 25,
            "lpe": 81048569,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 26743,
            "es2": 19969,
            "es3": 14969
        },
        {
            "CompetitorId": 610144,
            "CompetitorNumber": "27",
            "CompetitorName": "Bandito Deleto",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 29,
            "NumberOfLaps": 1223,
            "LastLaptime": 51344,
            "RaceTime": 86457239,
            "RunningTime": 86457239,
            "BestLaptime": 49518,
            "BestLapNumber": 60,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": false,
            "Retired": false,
            "GridPosition": 26,
            "PositionChange": 0,
            "Gap": "34 Laps",
            "gd": 982,
            "Behind": "124 Laps",
            "Split1": 21282,
            "Split2": 14908,
            "Split3": 15154,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 1,
            "el": 51344,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 41,
            "lpe": 84666112,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 21282,
            "es2": 14908,
            "es3": 15154
        },
        {
            "CompetitorId": 610145,
            "CompetitorNumber": "21",
            "CompetitorName": "BellyBoys Racing",
            "CompetitorClass": "RT10",
            "CompetitorSubClass": "Rookie",
            "DriverName": null,
            "Position": 30,
            "NumberOfLaps": 1220,
            "LastLaptime": 54362,
            "RaceTime": 86414482,
            "RunningTime": 86414482,
            "BestLaptime": 50506,
            "BestLapNumber": 95,
            "IsBestLapInRace": false,
            "IsCurrentLapPBestLap": false,
            "Seen": true,
            "InPit": true,
            "Retired": false,
            "GridPosition": 27,
            "PositionChange": 0,
            "Gap": "3 Laps",
            "gd": 2891,
            "Behind": "127 Laps",
            "Split1": 25959,
            "Split2": 17985,
            "Split3": null,
            "IsBestSector1": false,
            "pbs1": false,
            "IsBestSector2": false,
            "pbs2": false,
            "IsBestSector3": false,
            "pbs3": false,
            "cs": 3,
            "el": 59067,
            "TakenChequered": true,
            "ocl": true,
            "clnr": false,
            "blnr": false,
            "tt": null,
            "nat": null,
            "ps": 32,
            "lpe": 82792190,
            "nbc": "#000000",
            "nfc": "#FFFFFF",
            "es1": 25959,
            "es2": 17985,
            "es3": 15123
        }
    ]
}